### ISSUE TITLE
Research localizing date/time based on city returned

### ISSUE THREAD

**Issue by jesseschutt** [zaengle/laravel-security-notifications#3]
We have received complaints that the date/time in the security emails doesn't match the user's localized date/time, which makes sense because I'm assuming the value in the email isn't localized. 

Would it be possible to convert the time to whatever city is returned from the IP check?

**Comment by LoganTFox** [comment]
@jesseschutt this is ready to be tagged. I've added a constructor class to make sure we have the proper data.

**Comment by jesseschutt** [comment]
@LoganTFox - I saw the changes related to passing a data object which are a step in the right direction. Can you please review [this](https://youtu.be/nNtulOOZ0GY?si=KSfzSuh0pkK3ipNQ&t=520) and consider using an `\ArrayObject` instead?

**Comment by LoganTFox** [comment]
@jesseschutt here's my adjustment. Let me know what you think.

https://github.com/zaengle/laravel-security-notifications/commit/dd337fdc99460fd35a3ab1665773b7d131621a82

**Comment by jesseschutt** [comment]
> @jesseschutt here's my adjustment. Let me know what you think.
> 
> [dd337fd](https://github.com/zaengle/laravel-security-notifications/commit/dd337fdc99460fd35a3ab1665773b7d131621a82)

Love it! What do you think?
